sudo: required
services: 
  - docker

before_install:
  - docker build -t ruyonga/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true ruyonga/docker-react npm run test -- --coverage
language: generic 